import type { ActivityItem, KpiItem, StatusTone } from "./types";

export const executiveHeader = {
  projectName: "Plataforma Universitaria Integral (SyncUT)",
  status: "En desarrollo",
  version: "MVP Beta v1.0.0",
  updatedAt: new Date().toLocaleDateString("es-MX", { day: "2-digit", month: "short", year: "numeric" }),
  environment: "Production",
  leader: "Jassiel García",
  leaderRole: "Project Lead / Admin Master",
  online: true,
};

export const kpis: KpiItem[] = [
  { label: "Avance global", value: "78%", trend: "+8.4%", tone: "success", icon: "Gauge", micro: "18 tareas cerradas esta semana" },
  { label: "Tareas completadas", value: "128", trend: "+26", tone: "success", icon: "CheckCircle2", micro: "Sprints 1 y 2 en producción" },
  { label: "Tareas pendientes", value: "42", trend: "-12", tone: "info", icon: "ListTodo", micro: "28 en ejecución, 14 en backlog" },
  { label: "Bloqueos activos", value: "1", trend: "-4", tone: "warning", icon: "ShieldAlert", micro: "1 de integración externa" },
  { label: "Squads trabajando", value: "6", trend: "0", tone: "info", icon: "Users", micro: "28 integrantes totales" },
  { label: "Uptime sistema", value: "99.98%", trend: "+0.05%", tone: "success", icon: "Activity", micro: "Producción estable" },
  { label: "Commits semana", value: "30", trend: "+8", tone: "info", icon: "GitCommitHorizontal", micro: "Consolidación de ramas" },
  { label: "PRs aprobados", value: "12", trend: "+3", tone: "success", icon: "GitPullRequestArrow", micro: "Revisiones al día" },
  { label: "Módulos terminados", value: "4/7", trend: "+2", tone: "info", icon: "PackageCheck", micro: "Autenticación, Justificaciones, Dashboard, Notificaciones" },
];

export const roadmap = [
  {
    title: "Cierre de pruebas de conversión de retardos",
    priority: "Alta",
    owner: "Squad 1 · Justificaciones",
    eta: "12 Jun 2026",
    sprint: "Sprint 3",
    status: "in-progress" as StatusTone,
    dependency: "Estructura de perfiles de usuario",
  },
  {
    title: "Consolidación del motor de envío de correos",
    priority: "Alta",
    owner: "Squad 4 · Notificaciones",
    eta: "14 Jun 2026",
    sprint: "Sprint 3",
    status: "in-progress" as StatusTone,
    dependency: "Tokens de API e integración de Resend",
  },
  {
    title: "Implementación del semáforo de incidencias",
    priority: "Alta",
    owner: "Squad 5 · Incidencias",
    eta: "18 Jun 2026",
    sprint: "Sprint 3",
    status: "in-progress" as StatusTone,
    dependency: "Vistas y filtros de tutoría",
  },
  {
    title: "Hardening de políticas RLS y auditoría",
    priority: "Crítica",
    owner: "Squad 2 · Auditoría",
    eta: "15 Jun 2026",
    sprint: "Sprint 3",
    status: "in-progress" as StatusTone,
    dependency: "Migraciones de DB completadas",
  },
];

export const sprints = [
  {
    name: "Sprint 0 — Configuración inicial",
    progress: 100,
    total: 10,
    done: 10,
    owners: "Jassiel García",
    risks: "Sin riesgos",
    status: "completed" as StatusTone,
    deadline: "18 May 2026",
    dependencies: "Pnpm workspaces configurado",
  },
  {
    name: "Sprint 1 — Autenticación y Modelado",
    progress: 100,
    total: 24,
    done: 24,
    owners: "Squad 2 + Jassiel García",
    risks: "Riesgo bajo",
    status: "completed" as StatusTone,
    deadline: "25 May 2026",
    dependencies: "Esquemas Supabase iniciales",
  },
  {
    name: "Sprint 2 — Justificaciones e Integración",
    progress: 100,
    total: 35,
    done: 35,
    owners: "Squad 1 + Jassiel García",
    risks: "Riesgo medio",
    status: "completed" as StatusTone,
    deadline: "02 Jun 2026",
    dependencies: "Triggers de retardos a faltas",
  },
  {
    name: "Sprint 3 — Citas, Chatbot e Incidencias",
    progress: 68,
    total: 48,
    done: 32,
    owners: "Squads 3, 5, 6",
    risks: "Riesgo alto",
    status: "in-progress" as StatusTone,
    deadline: "16 Jun 2026",
    dependencies: "Webhooks y LDAP institucional",
  },
];

export const modules = [
  {
    name: "Autenticación",
    description: "Control de acceso seguro para alumnos, docentes y administrativos con roles Supabase.",
    objective: "Habilitar ingreso unificado y trazable.",
    impact: "Seguridad y aislamiento de datos.",
    mvpPriority: "Crítica",
    progress: 100,
    tasksDone: 15,
    tasksPending: 0,
    commits: 38,
    prsOpen: 0,
    bugs: 0,
    risk: "Bajo",
    techLead: "Ángel Zataráin",
    squad: "Squad 2 - Autenticación y Auditoría",
    assignees: ["Ángel Zataráin", "Alexander", "Alan", "Wallmach", "Erick"],
    nextSteps: ["Monitoreo de sesiones", "MFA adaptativo"],
    deliverables: ["Políticas RLS robustas", "Tokens de sesión seguros"],
    improvements: ["Trazabilidad inmutable"],
    dependencies: ["Profiles DB"],
    blockers: ["Ninguno"],
    history: [
      { by: "Ángel Zataráin", date: "01 Jun", type: "Feature", approval: "Aprobado", detail: "Creación de tablas base de perfiles y tokens." },
      { by: "Jassiel García", date: "05 Jun", type: "Feature", approval: "Aprobado", detail: "Acceso seguro y triggers para el usuario máster." },
    ],
  },
  {
    name: "Dashboard Gobernanza",
    description: "Tablero central ejecutivo con métricas reales de avance, commits y salud de base de datos.",
    objective: "Monitoreo del avance de todos los equipos en tiempo real.",
    impact: "Visibilidad integral y oportuna.",
    mvpPriority: "Alta",
    progress: 95,
    tasksDone: 12,
    tasksPending: 1,
    commits: 22,
    prsOpen: 0,
    bugs: 0,
    risk: "Bajo",
    techLead: "Jassiel García",
    squad: "Admin / PMO",
    assignees: ["Jassiel García"],
    nextSteps: ["Alertas en tiempo real con Supabase Broadcast", "Exportación PDF"],
    deliverables: ["Tablero ejecutivo final", "Sincronizador Git stats"],
    improvements: ["Integrar commits de ramas de forma dinámica"],
    dependencies: ["Git logs local", "Supabase Client"],
    blockers: ["Ninguno"],
    history: [
      { by: "Jassiel García", date: "05 Jun", type: "UI", approval: "Aprobado", detail: "Ajuste de UI al sistema de diseño unificado." },
    ],
  },
  {
    name: "Notificaciones",
    description: "Orquestación de avisos por correo y alertas internas para eventos académicos.",
    objective: "Asegurar comunicación oportuna y verificable.",
    impact: "Automatiza recordatorios de citas y justificaciones.",
    mvpPriority: "Alta",
    progress: 85,
    tasksDone: 18,
    tasksPending: 3,
    commits: 15,
    prsOpen: 1,
    bugs: 1,
    risk: "Medio",
    techLead: "Iván Vivanco",
    squad: "Squad 4 - Notificaciones",
    assignees: ["Iván Vivanco", "Fernando", "Vidales", "Ari", "Roman"],
    nextSteps: ["Envío de correos vía Resend", "Plantilla de justificaciones"],
    deliverables: ["Matriz de triggers de notificación", "Cola asíncrona de correos"],
    improvements: ["Políticas de reintento por falla"],
    dependencies: ["Supabase Edge Functions"],
    blockers: ["Sin credenciales de producción de Resend"],
    history: [
      { by: "Iván Vivanco", date: "03 Jun", type: "Docs", approval: "Aprobado", detail: "Definición del módulo de notificaciones y esquema de cola." },
    ],
  },
  {
    name: "Citas con Tutor",
    description: "Gestión de citas entre alumnos, docentes y tutores escolares.",
    objective: "Ordenar slots de disponibilidad.",
    impact: "Reduce inasistencias y colisiones de horarios.",
    mvpPriority: "Crítica",
    progress: 60,
    tasksDone: 12,
    tasksPending: 8,
    commits: 19,
    prsOpen: 2,
    bugs: 2,
    risk: "Alto",
    techLead: "Eduardo García",
    squad: "Squad 3 - Citas con Tutor",
    assignees: ["Eduardo García", "Karim", "Rivera", "Fernando Buendia"],
    nextSteps: ["Resolver colisiones de horario", "Integración con notificaciones"],
    deliverables: ["Calendario dinámico", "Catálogo de disponibilidad"],
    improvements: ["Cache de slots temporales"],
    dependencies: ["Estructura de profesores y alumnos"],
    blockers: ["Retraso en validación de horarios LDAP"],
    history: [
      { by: "Eduardo García", date: "01 Jun", type: "Docs", approval: "Aprobado", detail: "Creación de estructura de base de datos de citas." },
    ],
  },
  {
    name: "Justificaciones",
    description: "Flujo digital de justificación de inasistencias con evidencias físicas.",
    objective: "Agilizar trámites de faltas y retardos.",
    impact: "Reduce carga administrativa en control escolar.",
    mvpPriority: "Crítica",
    progress: 90,
    tasksDone: 22,
    tasksPending: 3,
    commits: 24,
    prsOpen: 1,
    bugs: 1,
    risk: "Medio",
    techLead: "Joel Chaparro",
    squad: "Squad 1 - Justificaciones",
    assignees: ["Joel Chaparro", "Alfonso", "Aaron Trejo", "Tania", "Karla", "Magdalena Silva"],
    nextSteps: ["Pruebas E2E de conversión de retardos", "Carga de archivos a bucket"],
    deliverables: ["Trigger de retardos a faltas", "Formulario de justificaciones"],
    improvements: ["Optimizar OCR de recetas médicas"],
    dependencies: ["Autenticación de estudiantes"],
    blockers: ["Pendiente validación de normativas legales"],
    history: [
      { by: "Joel Chaparro", date: "01 Jun", type: "Docs", approval: "Aprobado", detail: "Creación de documento esquema DB Justificaciones." },
      { by: "Magdalena Silva", date: "02 Jun", type: "Test", approval: "Aprobado", detail: "Pruebas de push a rama de justificaciones." },
    ],
  },
  {
    name: "Incidencias",
    description: "Registro de incidencias técnicas y operativas con semáforo de priorización.",
    objective: "Visualizar alertas tempranas en la tutoría.",
    impact: "Atención ágil a quejas y problemas del campus.",
    mvpPriority: "Media",
    progress: 50,
    tasksDone: 10,
    tasksPending: 10,
    commits: 21,
    prsOpen: 1,
    bugs: 2,
    risk: "Medio",
    techLead: "Osmara Araujo",
    squad: "Squad 5 - Incidencias",
    assignees: ["Osmara Araujo", "Marvin", "Kevin", "Aaron Mota"],
    nextSteps: ["Tablero semáforo semanal", "Reglas de escalamiento"],
    deliverables: ["Matriz de priorización de quejas", "Tablero visual"],
    improvements: ["Integrar notificaciones SMS en alertas rojas"],
    dependencies: ["Roles de coordinador"],
    blockers: ["Ninguno"],
    history: [
      { by: "Osmara Araujo", date: "02 Jun", type: "Docs", approval: "Aprobado", detail: "Definición de incidencias y reglas de semáforo." },
    ],
  },
  {
    name: "Chatbot",
    description: "Asistente inteligente para la resolución automática de dudas estudiantiles.",
    objective: "Reducir la carga de preguntas recurrentes.",
    impact: "Soporte escolar inmediato 24/7.",
    mvpPriority: "Media",
    progress: 40,
    tasksDone: 6,
    tasksPending: 10,
    commits: 11,
    prsOpen: 1,
    bugs: 0,
    risk: "Bajo",
    techLead: "Alexis",
    squad: "Squad 6 - Chatbot",
    assignees: ["Alexis", "Samantha", "Rey", "Pablo"],
    nextSteps: ["Base de conocimiento inicial", "Escalamiento a tutor"],
    deliverables: ["Interfaz de chat en portal", "FAQ estructurado"],
    improvements: ["Procesamiento de lenguaje natural avanzado"],
    dependencies: ["Temarios e información de trámites"],
    blockers: ["Falta dataset unificado de preguntas frecuentes"],
    history: [
      { by: "Alexis", date: "03 Jun", type: "UI", approval: "Aprobado", detail: "Maquetado de la interfaz de chat en el portal." },
    ],
  },
] as const;

export const globalActivity: ActivityItem[] = [
  { user: "Karla Vega", action: "merge", description: "Se fusiono rama feature/sso-role-lock para endurecer permisos.", module: "Autenticación", squad: "Squad 4", sprint: "Sprint 3", date: "17 May", time: "08:12", status: "Aprobado", impact: "Alto" },
  { user: "Raul Molina", action: "deploy", description: "Despliegue parcial de motor de disponibilidad con feature flag.", module: "Citas", squad: "Squad 3", sprint: "Sprint 3", date: "17 May", time: "07:30", status: "Exitoso", impact: "Medio" },
  { user: "Alejandra Rios", action: "validation", description: "Validacion de flujo de aprobacion de justificaciones con QA.", module: "Justificaciones", squad: "Squad 1", sprint: "Sprint 3", date: "16 May", time: "18:40", status: "Con observaciones", impact: "Alto" },
  { user: "Mateo Ceniceros", action: "hotfix", description: "Correccion de timeout en pipeline de auditoria de incidencias.", module: "Incidencias", squad: "Squad 2", sprint: "Sprint 2", date: "16 May", time: "14:05", status: "Aprobado", impact: "Medio" },
  { user: "Paulina Mora", action: "test", description: "Pruebas de carga del broker de notificaciones en 3 canales.", module: "Notificaciones", squad: "Squad 4", sprint: "Sprint 2", date: "15 May", time: "20:26", status: "Exitoso", impact: "Medio" },
  { user: "Daniela Ortega", action: "approval", description: "Aprobacion ejecutiva del tablero de KPI para direccion.", module: "Dashboard Base", squad: "PMO", sprint: "Sprint 3", date: "15 May", time: "11:12", status: "Aprobado", impact: "Alto" },
];

export const owners = [
  { name: "Daniela Ortega", squad: "PMO", role: "Project Lead", tasks: 14, progress: 84, weekly: "12 hitos", prs: 5, status: "activo" },
  { name: "Alejandra Rios", squad: "Squad 1", role: "Tech Lead", tasks: 11, progress: 72, weekly: "9 cambios", prs: 4, status: "revision" },
  { name: "Raul Molina", squad: "Squad 3", role: "Tech Lead", tasks: 13, progress: 79, weekly: "15 cambios", prs: 6, status: "activo" },
  { name: "Mateo Ceniceros", squad: "Squad 2", role: "Arquitecto", tasks: 9, progress: 63, weekly: "7 cambios", prs: 3, status: "pendiente" },
  { name: "Hector Ibarra", squad: "Squad 4", role: "Engineering Manager", tasks: 10, progress: 91, weekly: "11 cambios", prs: 4, status: "activo" },
  { name: "Nestor Cantu", squad: "Squad 2", role: "ML Engineer", tasks: 8, progress: 45, weekly: "6 cambios", prs: 2, status: "bloqueado" },
] as const;

export const improvements = [
  {
    title: "Normalizar criterios de severidad entre squads",
    impact: "Alto",
    priority: "Alta",
    owner: "PMO + QA Guild",
    recommendation: "Adoptar matriz unica de impacto/probabilidad para riesgos y bugs.",
    effort: "2 semanas",
  },
  {
    title: "Reducir deuda tecnica en integraciones externas",
    impact: "Alto",
    priority: "Alta",
    owner: "Arquitectura",
    recommendation: "Agregar capa anti-corruption para APIs institucionales heredadas.",
    effort: "3 semanas",
  },
  {
    title: "Mejorar throughput de revisiones de PR",
    impact: "Medio",
    priority: "Media",
    owner: "Tech Leads",
    recommendation: "Implementar policy de SLA por tamaño de cambio y reviewer backup.",
    effort: "1 semana",
  },
  {
    title: "Instrumentacion de trazabilidad funcional",
    impact: "Medio",
    priority: "Media",
    owner: "Data Team",
    recommendation: "Completar telemetria de embudo para citas y justificaciones.",
    effort: "2 semanas",
  },
] as const;

export const risks = [
  {
    risk: "Dependencia del webhook institucional para recordatorios",
    severity: "Critico",
    technicalImpact: "Bloquea envio programado en citas",
    operationalImpact: "Aumenta ausentismo y reprogramaciones",
    owner: "Squad 3",
    action: "Habilitar fallback SMTP y cola de reintentos",
    eta: "20 May 2026",
  },
  {
    risk: "Aprobacion juridica pendiente para flujo de evidencias",
    severity: "Medio",
    technicalImpact: "Retiene release de justificaciones",
    operationalImpact: "Continuidad parcial en tramite manual",
    owner: "Squad 1",
    action: "Mesa legal semanal y feature toggle",
    eta: "23 May 2026",
  },
  {
    risk: "Saturacion temporal en analitica semanal",
    severity: "Estable",
    technicalImpact: "Retraso en consolidacion de KPI",
    operationalImpact: "Reporte ejecutivo con latencia",
    owner: "Data Team",
    action: "Escalado horizontal nocturno",
    eta: "19 May 2026",
  },
] as const;

export const chartData = {
  squadProgress: [
    { squad: "S1", progreso: 68 },
    { squad: "S2", progreso: 59 },
    { squad: "S3", progreso: 79 },
    { squad: "S4", progreso: 92 },
  ],
  commitsByWeek: [
    { week: "W1", commits: 62 },
    { week: "W2", commits: 71 },
    { week: "W3", commits: 88 },
    { week: "W4", commits: 97 },
  ],
  tasksDone: [
    { sprint: "S0", completadas: 42 },
    { sprint: "S1", completadas: 58 },
    { sprint: "S2", completadas: 61 },
    { sprint: "S3", completadas: 49 },
  ],
  mvpAdvance: [
    { name: "Core", value: 84 },
    { name: "Operacion", value: 71 },
    { name: "Calidad", value: 66 },
  ],
  moduleDistribution: [
    { name: "Listo", value: 3 },
    { name: "En progreso", value: 4 },
  ],
  productivity: [
    { day: "L", valor: 73 },
    { day: "M", valor: 77 },
    { day: "X", valor: 81 },
    { day: "J", valor: 79 },
    { day: "V", valor: 76 },
  ],
  bugsBySprint: [
    { sprint: "S0", bugs: 3 },
    { sprint: "S1", bugs: 6 },
    { sprint: "S2", bugs: 11 },
    { sprint: "S3", bugs: 15 },
  ],
  healthScore: [
    { name: "Arquitectura", score: 82 },
    { name: "Calidad", score: 74 },
    { name: "Delivery", score: 78 },
    { name: "Riesgos", score: 64 },
  ],
};
